# Generated by Django 3.2.16 on 2023-01-24 09:33

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_netops_commit', '0002_commit_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='_custom_field_data',
            field=models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AddField(
            model_name='commit',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='commit',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
